### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'cargo'

### ISSUE THREAD

**Issue by Ralvke** [rust-lang/sublime-rust#192]
### Sublime Text Version
Sublime Text 3 (Build 3126)

### Rust Enhanced Version
2.0.1

### Operating system
Arch Linux

### Expected behavior
Code check

### Actual behavior
```
Syntax Check +706.622 Rust running: ['cargo', 'clippy', '--message-format=json']
Exception in thread Syntax Check:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "rust.rust_thread in /home/ralvke/.config/sublime-text-3/Installed Packages/Rust Enhanced.sublime-package", line 91, in _thread_run
  File "SyntaxCheckPlugin in /home/ralvke/.config/sublime-text-3/Installed Packages/Rust Enhanced.sublime-package", line 106, in run
  File "SyntaxCheckPlugin in /home/ralvke/.config/sublime-text-3/Installed Packages/Rust Enhanced.sublime-package", line 129, in get_rustc_messages
  File "rust.rust_proc in /home/ralvke/.config/sublime-text-3/Installed Packages/Rust Enhanced.sublime-package", line 226, in run
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'cargo'

>>> import subprocess
>>> subprocess.Popen(['cargo', 'clippy', '--message-format=json'])
<subprocess.Popen object at 0x7f226a038290>
```

**Comment by ehuss** [comment]
Can you tell me which login shell you have and is cargo in the PATH for that shell?  Rust Enhanced now uses [shellenv](https://github.com/codexns/shellenv) to ensure that Sublime uses the same environment as your login shell, and I'm guessing it is getting confused somehow.

I also assume this problem happens with `rust_syntax_checking_method` set to other values like `check`?

**Comment by Ralvke** [comment]
```
    "rust_env": {
    	"PATH": "/home/ralvke/.cargo/bin"
    },
```
Adding this to `RustEnhanced.sublime-settings` resolve this issue
