### ISSUE TITLE
Plugin does not start.

### ISSUE THREAD

**Issue by Phaiax** [rust-lang/sublime-rust#205]
### Sublime Text Version
Sublime Text 3 (Build 3126)

### Rust Enhanced Version
2.1.0

### Rust version
1.19 stable

### Operating system
Ubuntu 16.04

### Expected behavior
Error highlighting should start.

### Actual behavior
```
Syntax Check +43.086 Rust running: ['cargo', 'metadata', '--no-deps']
Exception in thread Syntax Check:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "rust.rust_thread in /home/daniel/.config/sublime-text-3/Installed Packages/Rust Enhanced.sublime-package", line 91, in _thread_run
  File "SyntaxCheckPlugin in /home/daniel/.config/sublime-text-3/Installed Packages/Rust Enhanced.sublime-package", line 106, in run
  File "SyntaxCheckPlugin in /home/daniel/.config/sublime-text-3/Installed Packages/Rust Enhanced.sublime-package", line 138, in get_rustc_messages
TypeError: get_command() got multiple values for argument 'initial_settings'
```

### Steps to reproduce
1. Don't know, I restarted sublime and now it has stopped working. Maybe the issue is apparent from the error message, otherwise I'll try to create a project to reproduce.

**Comment by ehuss** [comment]
It appears to be behaving as if it updated the plugin, but did not reload it completely.  I thought Package Control normally handled that.  Can you try restarting Sublime and see if that clears it up?

**Comment by Phaiax** [comment]
Did clear it up... thx :)
